FROM python:3.12-slim

WORKDIR /app

# Copy requirements and upgrade pip
COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code + model + scaler
COPY deploy.py .
COPY kmeans_model.pkl .
COPY scale.pkl .

EXPOSE 8000

CMD ["uvicorn", "deploy:app", "--host", "0.0.0.0", "--port", "8000"]
